# Contains a test code in which playerA wins 7-0. Copy and paste to the bottom of KubaGame.py to use

g = KubaGame(('playerA', 'W'), ('playerB', 'B'))
print(g.make_move('playerA', (1, 0), 'R'))
print(g.make_move('playerB', (1, 6), 'L'))
print(g.make_move('playerA', (1, 1), 'R'))
print(g.make_move('playerB', (0, 6), 'B'))
print(g.make_move('playerA', (1, 2), 'R'))
print(g.make_move('playerB', (0, 5), 'B'))
print(g.make_move('playerA', (1, 3), 'R'))
print(g.make_move('playerB', (2, 6), 'F'))
print(g.make_move('playerA', (1, 4), 'R'))
print(g.make_move('playerB', (0, 6), 'B'))
print(g.make_move('playerA', (1, 5), 'R'))
print(g.make_move('playerB', (6, 0), 'R'))
print(g.make_move('playerA', (2, 6), 'L'))
print(g.make_move('playerB', (6, 1), 'R'))
print(g.make_move('playerA', (2, 5), 'L'))
print(g.make_move('playerB', (6, 2), 'R'))
print(g.make_move('playerA', (2, 4), 'L'))
print(g.make_move('playerB', (6, 3), 'R'))
print(g.make_move('playerA', (2, 3), 'L'))
print(g.make_move('playerB', (6, 4), 'R'))
print(g.make_move('playerA', (2, 2), 'L'))
print(g.make_move('playerB', (6, 6), 'F'))
print(g.make_move('playerA', (2, 1), 'L'))
print(g.make_move('playerB', (5, 6), 'F'))
print(g.make_move('playerA', (3, 6), 'L'))
print(g.make_move('playerB', (4, 6), 'F'))
print(g.make_move('playerA', (5, 5), 'L'))
print(g.make_move('playerB', (3, 6), 'F'))
print(g.make_move('playerA', (3, 5), 'L'))
print(g.make_move('playerB', (2, 6), 'F'))
print(g.make_move('playerA', (3, 4), 'L'))
print(g.make_move('playerB', (1, 6), 'F'))
print("winner:", g.get_winner())  # should return None
print(g.make_move('playerA', (3, 3), 'L'))
print("playerA score:", g.get_captured('playerA'))  # should return 7
print("playerB score:", g.get_captured('playerB'))  # should return 0
print("winner:", g.get_winner())  # should return playerA
